// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmsTu2WJSOrBtkNnaIku1mNoXdvMDPVGg',
    appId: '1:456362860927:web:5b8eeb52b4e3d89dfa3a4a',
    messagingSenderId: '456362860927',
    projectId: 'fundmanagement-3c371',
    authDomain: 'fundmanagement-3c371.firebaseapp.com',
    storageBucket: 'fundmanagement-3c371.firebasestorage.app',
    measurementId: 'G-HXHV32P35L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYaJ3nCnrJE2zsuARflfw97TJRwzk26-g',
    appId: '1:456362860927:android:0e1861186ca98855fa3a4a',
    messagingSenderId: '456362860927',
    projectId: 'fundmanagement-3c371',
    storageBucket: 'fundmanagement-3c371.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUG9qfXF3I3pzMsFQcr6NnB2q2_m5e880',
    appId: '1:456362860927:ios:6ba3ad5f19fc7a78fa3a4a',
    messagingSenderId: '456362860927',
    projectId: 'fundmanagement-3c371',
    storageBucket: 'fundmanagement-3c371.firebasestorage.app',
    iosBundleId: 'com.example.fundManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUG9qfXF3I3pzMsFQcr6NnB2q2_m5e880',
    appId: '1:456362860927:ios:6ba3ad5f19fc7a78fa3a4a',
    messagingSenderId: '456362860927',
    projectId: 'fundmanagement-3c371',
    storageBucket: 'fundmanagement-3c371.firebasestorage.app',
    iosBundleId: 'com.example.fundManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmsTu2WJSOrBtkNnaIku1mNoXdvMDPVGg',
    appId: '1:456362860927:web:b285266a6956a8c7fa3a4a',
    messagingSenderId: '456362860927',
    projectId: 'fundmanagement-3c371',
    authDomain: 'fundmanagement-3c371.firebaseapp.com',
    storageBucket: 'fundmanagement-3c371.firebasestorage.app',
    measurementId: 'G-BN89JKEWFF',
  );
}
